version: "3"

services:
  app:
    build:
      context: .
      dockerfile: build/app/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    networks:
      - bridge-network
    depends_on:
      - db
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: build/worker/Dockerfile
    ports:
      - "3001:3001"
    restart: always
    networks:
      - bridge-network
    depends_on:
      - db
      - rabbitmq

  db:
    image: mariadb:10.10.1-rc-jammy
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maintenance
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    networks:
      - bridge-network
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./build/database:/docker-entrypoint-initdb.d
    logging:
      driver: none

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bridge-network
    logging:
      driver: none

networks:
  bridge-network:
    driver: bridge

volumes:
  mariadb-data: