// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/notification/repository/notificationRepository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	model "maintenance-task/pkg/notification/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNotificationRepository is a mock of NotificationRepository interface.
type MockNotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepositoryMockRecorder
}

// MockNotificationRepositoryMockRecorder is the mock recorder for MockNotificationRepository.
type MockNotificationRepositoryMockRecorder struct {
	mock *MockNotificationRepository
}

// NewMockNotificationRepository creates a new mock instance.
func NewMockNotificationRepository(ctrl *gomock.Controller) *MockNotificationRepository {
	mock := &MockNotificationRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepository) EXPECT() *MockNotificationRepositoryMockRecorder {
	return m.recorder
}

// ClearNotifications mocks base method.
func (m *MockNotificationRepository) ClearNotifications(userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearNotifications", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearNotifications indicates an expected call of ClearNotifications.
func (mr *MockNotificationRepositoryMockRecorder) ClearNotifications(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearNotifications", reflect.TypeOf((*MockNotificationRepository)(nil).ClearNotifications), userID)
}

// CreateNotification mocks base method.
func (m *MockNotificationRepository) CreateNotification(input model.CreateNotification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotification", input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNotification indicates an expected call of CreateNotification.
func (mr *MockNotificationRepositoryMockRecorder) CreateNotification(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotification", reflect.TypeOf((*MockNotificationRepository)(nil).CreateNotification), input)
}

// DeleteNotification mocks base method.
func (m *MockNotificationRepository) DeleteNotification(notificationID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNotification", notificationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNotification indicates an expected call of DeleteNotification.
func (mr *MockNotificationRepositoryMockRecorder) DeleteNotification(notificationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNotification", reflect.TypeOf((*MockNotificationRepository)(nil).DeleteNotification), notificationID)
}

// ListNotifications mocks base method.
func (m *MockNotificationRepository) ListNotifications(userID int) ([]*model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotifications", userID)
	ret0, _ := ret[0].([]*model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotifications indicates an expected call of ListNotifications.
func (mr *MockNotificationRepositoryMockRecorder) ListNotifications(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotifications", reflect.TypeOf((*MockNotificationRepository)(nil).ListNotifications), userID)
}
